import streamlit as st

# ตั้งค่าหน้าเพจของ Streamlit ให้เป็นแบบกว้าง (Wide Layout) และซ่อน Sidebar
st.set_page_config(
    page_title="Asia Mineral Supply (AMS) - Premium Mineral Supplier",
    page_icon="💎",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# ประกาศโค้ด HTML แบบบรรทัดต่อบรรทัด (Line-by-Line List) 
# เพื่อป้องกัน SyntaxError จากเครื่องหมายคำพูดซ้อนกัน และช่วยให้แก้ไขโค้ดง่ายขึ้น
html_lines = [
    '<!DOCTYPE html>',
    '<html lang="en" class="scroll-smooth" style="scroll-behavior: smooth;">',
    '<head>',
    '    <meta charset="UTF-8">',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '    <title>Asia Mineral Supply (AMS)</title>',
    '    <script src="https://cdn.tailwindcss.com"></script>',
    '    <link rel="preconnect" href="https://fonts.googleapis.com">',
    '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">',
    '    <style>',
    '        body {',
    '            font-family: "Plus Jakarta Sans", "Inter", sans-serif;',
    '            background-color: #f8fafc;',
    '            color: #1e293b;',
    '            overflow-y: auto;',
    '        }',
    '        .font-serif {',
    '            font-family: "Playfair Display", serif;',
    '        }',
    '    </style>',
    '</head>',
    '<body class="bg-[#f8fafc] min-h-screen">',
    '',
    '    <!-- 1. NAVIGATION BAR (Sticky Menu) -->',
    '    <nav class="sticky top-0 z-50 bg-[#0b2c3d] text-white shadow-xl border-b border-slate-800">',
    '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
    '            <div class="flex items-center justify-between h-20">',
    '                <div class="flex items-center">',
    '                    <div class="flex-shrink-0 flex flex-col">',
    '                        <span class="font-serif text-2xl font-bold tracking-wider text-[#c5a059]">AMS</span>',
    '                        <span class="text-xs tracking-widest text-slate-400 font-light -mt-1">ASIA MINERAL SUPPLY</span>',
    '                    </div>',
    '                </div>',
    '                <!-- Desktop Menu Links -->',
    '                <div class="hidden md:block">',
    '                    <div class="ml-10 flex items-center space-x-8 text-sm font-medium tracking-wide">',
    '                        <a href="#about" class="hover:text-[#c5a059] transition-colors duration-300">About Us</a>',
    '                        <a href="#products" class="hover:text-[#c5a059] transition-colors duration-300">Products</a>',
    '                        <a href="#manufacturing" class="hover:text-[#c5a059] transition-colors duration-300">Manufacturing & QC</a>',
    '                        <a href="#applications" class="hover:text-[#c5a059] transition-colors duration-300">Applications</a>',
    '                        <a href="#contact" class="hover:text-[#c5a059] transition-colors duration-300">Contact Us</a>',
    '                        <a href="#contact" class="bg-[#c5a059] text-[#0b2c3d] px-5 py-2.5 rounded font-semibold shadow-lg hover:bg-[#b38f48] transition-all duration-300 transform hover:-translate-y-0.5">Request Quote / COA</a>',
    '                    </div>',
    '                </div>',
    '                <!-- Mobile menu button -->',
    '                <div class="md:hidden">',
    '                    <button id="mobile-menu-button" class="text-slate-300 hover:text-white focus:outline-none p-2">',
    '                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">',
    '                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />',
    '                        </svg>',
    '                    </button>',
    '                </div>',
    '            </div>',
    '        </div>',
    '        <!-- Mobile Dropdown Menu -->',
    '        <div id="mobile-menu" class="hidden md:hidden bg-[#0b2c3d] px-4 pt-2 pb-4 space-y-2 border-t border-slate-800">',
    '            <a href="#about" class="mobile-nav-link block text-slate-300 hover:text-white py-2">About Us</a>',
    '            <a href="#products" class="mobile-nav-link block text-slate-300 hover:text-white py-2">Products</a>',
    '            <a href="#manufacturing" class="mobile-nav-link block text-slate-300 hover:text-white py-2">Manufacturing & QC</a>',
    '            <a href="#applications" class="mobile-nav-link block text-slate-300 hover:text-white py-2">Applications</a>',
    '            <a href="#contact" class="mobile-nav-link block text-slate-300 hover:text-white py-2">Contact Us</a>',
    '            <a href="#contact" class="mobile-nav-link block bg-[#c5a059] text-[#0b2c3d] text-center px-4 py-2 rounded font-semibold mt-4">Request Quote / COA</a>',
    '        </div>',
    '    </nav>',
    '',
    '    <!-- 2. HERO SECTION -->',
    '    <header class="relative bg-[#0b2c3d] text-white overflow-hidden py-24 lg:py-32">',
    '        <div class="absolute inset-0 opacity-10">',
    '            <div class="absolute top-0 left-0 w-full h-full bg-[radial-gradient(#c5a059_1px,transparent_1px)] [background-size:16px_16px]"></div>',
    '        </div>',
    '        <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
    '            <div class="lg:w-2/3">',
    '                <span class="inline-block border border-[#c5a059] text-[#c5a059] font-medium text-xs uppercase tracking-widest px-3 py-1 rounded-full mb-6">World-Class Industrial Minerals</span>',
    '                <h1 class="font-serif text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight leading-tight mb-6">',
    '                    Reliable supply of powder <br><span class="text-[#c5a059]">Barium Sulphate (BaSO₄)</span> & Talc',
    '                </h1>',
    '                <p class="text-lg sm:text-xl text-slate-300 max-w-2xl font-light leading-relaxed mb-10">',
    '                    Partnering with Asian Mineral Resources (AMR). Over 30 years of premier mineral processing heritage in Saraburi, Thailand. Delivering ultra-pure minerals globally.',
    '                </p>',
    '                <div class="flex flex-col sm:flex-row gap-4">',
    '                    <a href="#products" class="bg-[#c5a059] text-[#0b2c3d] px-8 py-3.5 rounded font-semibold shadow-lg text-center hover:bg-[#b38f48] transition-all duration-300 transform hover:-translate-y-0.5">',
    '                        Download Technical Specs',
    '                    </a>',
    '                    <a href="#contact" class="border border-slate-500 text-white px-8 py-3.5 rounded font-semibold text-center hover:bg-slate-800 hover:border-white transition-all duration-300">',
    '                        Contact Sales',
    '                    </a>',
    '                </div>',
    '            </div>',
    '        </div>',
    '    </header>',
    '',
    '    <!-- 3. ABOUT US SECTION -->',
    '    <section id="about" class="py-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
    '        <div class="grid lg:grid-cols-12 gap-16 items-center">',
    '            <div class="lg:col-span-5">',
    '                <span class="text-xs font-bold tracking-widest text-[#c5a059] uppercase block mb-2">Corporate Profile</span>',
    '                <h2 class="font-serif text-3xl sm:text-4xl font-bold text-[#0b2c3d] mb-6">Strategic Partnership in Mineral Processing</h2>',
    '                <p class="text-slate-600 leading-relaxed mb-6">',
    '                    <strong>Asia Mineral Supply (AMS)</strong> acts as the exclusive Sales & Marketing arm to <strong>Asian Mineral Resources (AMR)</strong>, our affiliated production hub with over 30 years of extensive grinding mill expertise.',
    '                </p>',
    '                <p class="text-slate-600 leading-relaxed mb-8">',
    '                    Strategically located 120 kilometers east of Bangkok at the center of <strong>Saraburi</strong>—the historical heartland of Thailand\'s mineral grinding industry—our facility enables streamlined logistics directly to the Bangkok Port for rapid international shipment.',
    '                </p>',
    '                <div class="border-l-4 border-[#c5a059] pl-4 italic text-slate-700 bg-slate-100 p-4 rounded-r shadow-sm">',
    '                    "Dedicated to supplying natural premium functional fillers ranging from ultra-fine 5 micron powders to industry-standard 325 mesh aggregates."',
    '                </div>',
    '            </div>',
    '            <div class="lg:col-span-7">',
    '                <h3 class="text-xl font-bold text-[#0b2c3d] mb-6 flex items-center">',
    '                    <span class="bg-[#0b2c3d] text-white w-2 h-6 inline-block mr-3"></span>',
    '                    Global Supply Diversity & Chain Security',
    '                </h3>',
    '                <div class="grid sm:grid-cols-3 gap-6">',
    '                    <div class="bg-white p-6 rounded-lg shadow-md border-t-4 border-[#0b2c3d]">',
    '                        <div class="text-[#c5a059] font-bold text-lg mb-2">China</div>',
    '                        <p class="text-sm text-slate-600 leading-relaxed">High quality reserves backed by abundant, established geological deposits ensuring long-term volume stability.</p>',
    '                    </div>',
    '                    <div class="bg-white p-6 rounded-lg shadow-md border-t-4 border-[#c5a059]">',
    '                        <div class="text-[#0b2c3d] font-bold text-lg mb-2">Laos</div>',
    '                        <p class="text-sm text-slate-600 leading-relaxed">Immediate cross-border logistical access. Strict pre-wash and tailored ore selection controls enforced at the frontier.</p>',
    '                    </div>',
    '                    <div class="bg-white p-6 rounded-lg shadow-md border-t-4 border-slate-400">',
    '                        <div class="text-slate-500 font-bold text-lg mb-2">Pakistan</div>',
    '                        <p class="text-sm text-slate-600 leading-relaxed">Alternative supply channels offering highly acceptable grade quality, with ongoing supply capability verification.</p>',
    '                    </div>',
    '                </div>',
    '            </div>',
    '        </div>',
    '    </section>',
    '',
    '    <!-- 4. PRODUCTION & TECH SPECS SECTION -->',
    '    <section id="manufacturing" class="py-24 bg-slate-900 text-white">',
    '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
    '            <div class="text-center max-w-3xl mx-auto mb-16">',
    '                <span class="text-xs font-bold tracking-widest text-[#c5a059] uppercase block mb-2">Industrial Capacity</span>',
    '                <h2 class="font-serif text-3xl sm:text-4xl font-bold mb-4">Advanced Grinding Infrastructure</h2>',
    '                <p class="text-slate-400">Operating 5 highly customized processing lines running 16 hours a day to deliver over 25,000+ MT annual output capacity of Barytes and high-grade Talc.</p>',
    '            </div>',
    '            <div class="grid sm:grid-cols-2 lg:grid-cols-5 gap-6 mb-20">',
    '                <div class="bg-slate-800 p-6 rounded border border-slate-700 hover:border-[#c5a059] transition-all">',
    '                    <div class="text-xs text-slate-400 uppercase tracking-wider mb-1">Line 1: Super Fine</div>',
    '                    <div class="text-xl font-bold text-[#c5a059] mb-2">2,500 MT / Year</div>',
    '                    <p class="text-xs text-slate-300">Down to 5 Micron ultra-fine classification for premium applications.</p>',
    '                </div>',
    '                <div class="bg-slate-800 p-6 rounded border border-slate-700 hover:border-[#c5a059] transition-all">',
    '                    <div class="text-xs text-slate-400 uppercase tracking-wider mb-1">Line 2: Fine Grade</div>',
    '                    <div class="text-xl font-bold text-[#c5a059] mb-2">7,500 MT / Year</div>',
    '                    <p class="text-xs text-slate-300">Targeted sizing protocols at 5µ, 7µ, and 10µ distributions.</p>',
    '                </div>',
    '                <div class="bg-slate-800 p-6 rounded border border-slate-700 hover:border-[#c5a059] transition-all">',
    '                    <div class="text-xs text-slate-400 uppercase tracking-wider mb-1">Line 3: Fine Grade</div>',
    '                    <div class="text-xl font-bold text-[#c5a059] mb-2">7,500 MT / Year</div>',
    '                    <p class="text-xs text-slate-300">Parallel manufacturing line specialized in sharp particle distribution.</p>',
    '                </div>',
    '                <div class="bg-slate-800 p-6 rounded border border-slate-700 hover:border-[#c5a059] transition-all">',
    '                    <div class="text-xs text-slate-400 uppercase tracking-wider mb-1">Line 4: API Barytes</div>',
    '                    <div class="text-xl font-bold text-[#c5a059] mb-2">15,000 MT / Year</div>',
    '                    <p class="text-xs text-slate-300">Dedicated high-density milling for functional heavy weighting agents.</p>',
    '                </div>',
    '                <div class="bg-slate-800 p-6 rounded border border-slate-700 hover:border-[#c5a059] transition-all">',
    '                    <div class="text-xs text-slate-400 uppercase tracking-wider mb-1">Line 5: API Barytes</div>',
    '                    <div class="text-xl font-bold text-[#c5a059] mb-2">15,000 MT / Year</div>',
    '                    <p class="text-xs text-slate-300">Scale replication ensuring zero downtime and continuous strategic output.</p>',
    '                </div>',
    '            </div>',
    '            ',
    '            <!-- Interactive Product Tabs -->',
    '            <div class="bg-slate-800 rounded-xl p-6 sm:p-8 border border-slate-700 shadow-2xl">',
    '                <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center border-b border-slate-700 pb-6 mb-8 gap-4">',
    '                    <div>',
    '                        <h3 class="text-2xl font-bold font-serif text-white">Interactive Specifications Portal</h3>',
    '                        <p class="text-xs text-slate-400 mt-1">Verified via SediGraph (Micromeritics) methodology & KETT Reflectometer controls</p>',
    '                    </div>',
    '                    <div class="flex bg-slate-900 p-1.5 rounded-lg border border-slate-700">',
    '                        <button id="btn-baso4" class="px-4 py-2 text-sm rounded font-medium bg-[#c5a059] text-[#0b2c3d] transition-all">',
    '                            Barium Sulphate (BaSO₄)',
    '                        </button>',
    '                        <button id="btn-talc" class="px-4 py-2 text-sm rounded font-medium text-slate-400 hover:text-white transition-all">',
    '                            Talc Ranges',
    '                        </button>',
    '                    </div>',
    '                </div>',
    '                ',
    '                <!-- BaSO4 Panel -->',
    '                <div id="baso4-panel" class="overflow-x-auto">',
    '                    <table class="w-full text-left border-collapse text-sm">',
    '                        <thead>',
    '                            <tr class="border-b border-slate-700 text-[#c5a059] uppercase tracking-wider text-xs">',
    '                                <th class="pb-3 pl-2">Product Name</th>',
    '                                <th class="pb-3">BaSO₄ Min.</th>',
    '                                <th class="pb-3">Top Cut (d98)</th>',
    '                                <th class="pb-3">Average Size</th>',
    '                                <th class="pb-3">Whiteness Index</th>',
    '                                <th class="pb-3">Specific Gravity</th>',
    '                                <th class="pb-3 pr-2">Moisture Max.</th>',
    '                            </tr>',
    '                        </thead>',
    '                        <tbody class="divide-y divide-slate-700 text-slate-300">',
    '                            <tr class="hover:bg-slate-700/50">',
    '                                <td class="py-3 pl-2 font-semibold text-white">Microbytes 2</td><td>&gt;98.0%</td><td>14 µ</td><td>2 µ</td><td>&gt;93%</td><td>&gt;4.20</td><td class="pr-2">0.1%</td>',
    '                            </tr>',
    '                            <tr class="hover:bg-slate-700/50">',
    '                                <td class="py-3 pl-2 font-semibold text-white">Microbytes 5</td><td>96.7%</td><td>20 µ</td><td>5 µ</td><td>91%</td><td>&gt;4.20</td><td class="pr-2">0.1%</td>',
    '                            </tr>',
    '                            <tr class="hover:bg-slate-700/50">',
    '                                <td class="py-3 pl-2 font-semibold text-white">Microbytes 7</td><td>96.7%</td><td>25 µ</td><td>7 µ</td><td>91%</td><td>&gt;4.20</td><td class="pr-2">0.1%</td>',
    '                            </tr>',
    '                            <tr class="hover:bg-slate-700/50">',
    '                                <td class="py-3 pl-2 font-semibold text-white">Microbytes 10</td><td>96.7%</td><td>30 µ</td><td>10 µ</td><td>91%</td><td>&gt;4.20</td><td class="pr-2">0.1%</td>',
    '                            </tr>',
    '                            <tr class="hover:bg-slate-700/50">',
    '                                <td class="py-3 pl-2 font-semibold text-white">Milbar 5 / 7 / 10</td><td>96.7%</td><td>20/25/30 µ</td><td>5/7/10 µ</td><td>89%</td><td>&gt;4.20</td><td class="pr-2">0.1%</td>',
    '                            </tr>',
    '                            <tr class="hover:bg-slate-700/50">',
    '                                <td class="py-3 pl-2 font-semibold text-white">Milbar A45</td><td>96.7%</td><td>45 µ</td><td>14 µ</td><td>90%</td><td>&gt;4.20</td><td class="pr-2">0.1%</td>',
    '                            </tr>',
    '                            <tr class="hover:bg-slate-700/50">',
    '                                <td class="py-3 pl-2 font-semibold text-white">Milbar D45</td><td>93.0%</td><td>45 µ</td><td>14 µ</td><td>60%</td><td>3.90-4.00</td><td class="pr-2">0.1%</td>',
    '                            </tr>',
    '                        </tbody>',
    '                    </table>',
    '                </div>',
    '                ',
    '                <!-- Talc Panel -->',
    '                <div id="talc-panel" class="hidden overflow-x-auto">',
    '                    <table class="w-full text-left border-collapse text-sm">',
    '                        <thead>',
    '                            <tr class="border-b border-slate-700 text-[#c5a059] uppercase tracking-wider text-xs">',
    '                                <th class="pb-3 pl-2">Product Name</th>',
    '                                <th class="pb-3">Top Size Max</th>',
    '                                <th class="pb-3">Median Particle Size</th>',
    '                                <th class="pb-3">Whiteness Index</th>',
    '                                <th class="pb-3">Primary Applications</th>',
    '                                <th class="pb-3 pr-2">Sterilization Available</th>',
    '                            </tr>',
    '                        </thead>',
    '                        <tbody class="divide-y divide-slate-700 text-slate-300">',
    '                            <tr class="hover:bg-slate-700/50">',
    '                                <td class="py-4 pl-2 font-semibold text-white">Talcon BC20</td><td>20 µ</td><td>6.0-7.0 µ</td><td class="text-[#c5a059] font-medium">91%</td><td>Industrial Rubber Thread</td><td class="pr-2 text-emerald-400">Yes</td>',
    '                            </tr>',
    '                            <tr class="hover:bg-slate-700/50">',
    '                                <td class="py-4 pl-2 font-semibold text-white">Talcon BC45</td><td>45 µ</td><td>12.0-15.0 µ</td><td class="text-[#c5a059] font-medium">90%</td><td>Cosmetics & High-Grade Paints</td><td class="pr-2 text-emerald-400">Yes</td>',
    '                            </tr>',
    '                        </tbody>',
    '                    </table>',
    '                </div>',
    '            </div>',
    '        </div>',
    '    </section>',
    '',
    '    <!-- 5. APPLICATIONS SECTION -->',
    '    <section id="applications" class="py-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
    '        <div class="text-center max-w-3xl mx-auto mb-16">',
    '            <span class="text-xs font-bold tracking-widest text-[#c5a059] uppercase block mb-2">Cross-Industry Solutions</span>',
    '            <h2 class="font-serif text-3xl sm:text-4xl font-bold text-[#0b2c3d]">Tailored Industry Performance</h2>',
    '        </div>',
    '        <div class="grid md:grid-cols-3 gap-8">',
    '            <div class="bg-white p-8 rounded-xl shadow-sm border border-slate-100 hover:shadow-xl transition-all duration-300">',
    '                <div class="w-12 h-12 rounded-lg bg-slate-100 flex items-center justify-center text-[#c5a059] mb-6">',
    '                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01" /></svg>',
    '                </div>',
    '                <h3 class="text-xl font-bold text-[#0b2c3d] mb-4">Color, Paint & Extenders</h3>',
    '                <p class="text-sm text-slate-600 leading-relaxed mb-4">Specialized 15% loading formulas for high-end powder coating, architectural fillers to optimize scrub-resistance in decorative paints.</p>',
    '            </div>',
    '            <div class="bg-white p-8 rounded-xl shadow-sm border border-slate-100 hover:shadow-xl transition-all duration-300">',
    '                <div class="w-12 h-12 rounded-lg bg-slate-100 flex items-center justify-center text-[#c5a059] mb-6">',
    '                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg>',
    '                </div>',
    '                <h3 class="text-xl font-bold text-[#0b2c3d] mb-4">Plastics & Polymers</h3>',
    '                <p class="text-sm text-slate-600 leading-relaxed mb-4">Ideal structural weighting agent integrated into technical PP compounding. Provides dense, low-cost functional white base extenders.</p>',
    '            </div>',
    '            <div class="bg-white p-8 rounded-xl shadow-sm border border-slate-100 hover:shadow-xl transition-all duration-300">',
    '                <div class="w-12 h-12 rounded-lg bg-slate-100 flex items-center justify-center text-[#c5a059] mb-6">',
    '                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg>',
    '                </div>',
    '                <h3 class="text-xl font-bold text-[#0b2c3d] mb-4">Friction, Seals & Drilling</h3>',
    '                <p class="text-sm text-slate-600 leading-relaxed mb-4">Heavy-duty structural base for brake pad lining and primers. Fully compliant API standard oil-drilling grade mud-weighting agents (T-Bar 200).</p>',
    '            </div>',
    '        </div>',
    '    </section>',
    '',
    '    <!-- 6. CONTACT & QUOTE REQUEST FORM -->',
    '    <section id="contact" class="py-24 bg-slate-50 border-t border-slate-200">',
    '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
    '            <div class="grid lg:grid-cols-12 gap-16">',
    '                <div class="lg:col-span-5">',
    '                    <span class="text-xs font-bold tracking-widest text-[#c5a059] uppercase block mb-2">Connect With Us</span>',
    '                    <h2 class="font-serif text-3xl font-bold text-[#0b2c3d] mb-6">Request Samples & Technical Documentation</h2>',
    '                    <p class="text-slate-600 mb-8 leading-relaxed">Secure certified copies of our Certificate of Analysis (COA), Technical Data Sheets (TDS), or request specific laboratory-grade samples for your compounding trials.</p>',
    '                    <div class="space-y-6">',
    '                        <div class="flex items-start">',
    '                            <div class="text-[#c5a059] mt-1 mr-4">',
    '                                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg>',
    '                            </div>',
    '                            <div>',
    '                                <h4 class="font-bold text-[#0b2c3d]">Production Plant Location</h4>',
    '                                <p class="text-sm text-slate-600 mt-1">Saraburi Industrial Grinding Hub (120 km from Bangkok Port), Thailand.</p>',
    '                            </div>',
    '                        </div>',
    '                        <div class="flex items-start">',
    '                            <div class="text-[#c5a059] mt-1 mr-4">',
    '                                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L22 8m-9 13h4a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>',
    '                            </div>',
    '                            <div>',
    '                                <h4 class="font-bold text-[#0b2c3d]">Commercial Correspondence</h4>',
    '                                <p class="text-sm text-slate-600 mt-1">sales@asiamineralsupply.com</p>',
    '                            </div>',
    '                        </div>',
    '                    </div>',
    '                </div>',
    '                ',
    '                <div class="lg:col-span-7 bg-white p-8 rounded-xl shadow-md border border-slate-100">',
    '                    <form id="quote-form" class="grid sm:grid-cols-2 gap-6" onsubmit="event.preventDefault(); alert(\'Thank you for your interest. Our B2B Sales Representative will reach out to your organization within 24 business hours.\');">',
    '                        <div>',
    '                            <label class="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-2">Corporate Name *</label>',
    '                            <input type="text" required class="w-full border border-slate-300 rounded px-4 py-2.5 text-sm focus:outline-none focus:border-[#0b2c3d]">',
    '                        </div>',
    '                        <div>',
    '                            <label class="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-2">Work Email *</label>',
    '                            <input type="email" required class="w-full border border-slate-300 rounded px-4 py-2.5 text-sm focus:outline-none focus:border-[#0b2c3d]">',
    '                        </div>',
    '                        <div>',
    '                            <label class="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-2">Target Product Grade *</label>',
    '                            <select class="w-full border border-slate-300 rounded bg-white px-4 py-2.5 text-sm focus:outline-none focus:border-[#0b2c3d]">',
    '                                <option>Microbytes Series (BaSO4 ultra-fine)</option>',
    '                                <option>Milbar Series (BaSO4 premium)</option>',
    '                                <option>Milbar Industrial Grades (A45 / D45)</option>',
    '                                <option>Talcon Talc Series (BC20 / BC45)</option>',
    '                                <option>T-Bar 200 (API Drilling Grade)</option>',
    '                            </select>',
    '                        </div>',
    '                        <div>',
    '                            <label class="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-2">Inquiry Type *</label>',
    '                            <select class="w-full border border-slate-300 rounded bg-white px-4 py-2.5 text-sm focus:outline-none focus:border-[#0b2c3d]">',
    '                                <option>Request Official Quotation</option>',
    '                                <option>Request Lab-Sample & Technical Data Sheet</option>',
    '                            </select>',
    '                        </div>',
    '                        <div class="sm:col-span-2">',
    '                            <label class="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-2">Application Specifics / Annual Tonnage Needs</label>',
    '                            <textarea rows="4" class="w-full border border-slate-300 rounded px-4 py-2.5 text-sm focus:outline-none focus:border-[#0b2c3d]" placeholder="Describe your industrial parameters..."></textarea>',
    '                        </div>',
    '                        <div class="sm:col-span-2">',
    '                            <button type="submit" class="w-full bg-[#0b2c3d] text-white font-semibold py-3 rounded shadow hover:bg-slate-800 transition-colors uppercase tracking-wider text-sm">Submit B2B Request</button>',
    '                        </div>',
    '                    </form>',
    '                </div>',
    '            </div>',
    '        </div>',
    '    </section>',
    '',
    '    <footer class="bg-[#0b2c3d] text-slate-400 py-12 text-center text-xs border-t border-slate-800">',
    '        <p class="tracking-wide">&copy; 2026 Asia Mineral Supply (AMS). All Rights Reserved.</p>',
    '    </footer>',
    '',
    '    <!-- Client-Side Tab & Toggle Scripts -->',
    '    <script>',
    '        window.addEventListener("DOMContentLoaded", () => {',
    '            const btnBaso4 = document.getElementById("btn-baso4");',
    '            const btnTalc = document.getElementById("btn-talc");',
    '            const baso4Panel = document.getElementById("baso4-panel");',
    '            const talcPanel = document.getElementById("talc-panel");',
    '            ',
    '            if (btnBaso4 && btnTalc && baso4Panel && talcPanel) {',
    '                btnBaso4.addEventListener("click", (e) => {',
    '                    e.preventDefault();',
    '                    baso4Panel.classList.remove("hidden");',
    '                    talcPanel.classList.add("hidden");',
    '                    btnBaso4.className = "px-4 py-2 text-sm rounded font-medium bg-[#c5a059] text-[#0b2c3d] transition-all shadow-md";',
    '                    btnTalc.className = "px-4 py-2 text-sm rounded font-medium text-slate-400 hover:text-white transition-all";',
    '                });',
    '                ',
    '                btnTalc.addEventListener("click", (e) => {',
    '                    e.preventDefault();',
    '                    talcPanel.classList.remove("hidden");',
    '                    baso4Panel.classList.add("hidden");',
    '                    btnTalc.className = "px-4 py-2 text-sm rounded font-medium bg-[#c5a059] text-[#0b2c3d] transition-all shadow-md";',
    '                    btnBaso4.className = "px-4 py-2 text-sm rounded font-medium text-slate-400 hover:text-white transition-all";',
    '                });',
    '            }',
    '            ',
    '            // Mobile Responsive Menu Controller',
    '            const menuBtn = document.getElementById("mobile-menu-button");',
    '            const mobileMenu = document.getElementById("mobile-menu");',
    '            if (menuBtn && mobileMenu) {',
    '                menuBtn.addEventListener("click", (e) => {',
    '                    e.preventDefault();',
    '                    mobileMenu.classList.toggle("hidden");',
    '                });',
    '                ',
    '                document.querySelectorAll(".mobile-nav-link").forEach(link => {',
    '                    link.addEventListener("click", () => {',
    '                        mobileMenu.classList.add("hidden");',
    '                    });',
    '                });',
    '            }',
    '        });',
    '    </script>',
    '</body>',
    '</html>'
]

# เชื่อมต่อลิสต์ข้อความทั้งหมดเข้าด้วยกันเป็นก้อน HTML ชิ้นเดียวที่สมบูรณ์และปลอดภัย
clean_html_code = '\n'.join(html_lines)

# แสดงผลแบบ Component Sandbox ที่มีแถบเลื่อนข้างใน (scrolling=True)
# ทำให้ Anchor Link ทำงานเลื่อนหน้าจอภายในเว็บได้อย่างแม่นยำและสมบูรณ์
st.components.v1.html(clean_html_code, height=900, scrolling=True)
